module.exports = {
	cambridge: 'https://dictionary.cambridge.org/',
	chrome: `"C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe"`,
	discord: `"$env:USERPROFILE\\AppData\\Local\\Discord\\app-1.0.9011\\Discord.exe"`,
	figma: `"$env:USERPROFILE\\AppData\\Local\\Figma\\app-116.7.103\\Figma.exe"`,
	google_image: 'https://images.google.com/',
	google_keep: 'https://keep.google.com/',
	google_map: 'https://maps.google.com/',
	google_translate: 'https://translate.google.com/',
	miro: 'https://miro.com/',
	oxford: 'https://www.oxfordlearnersdictionaries.com/',
	shareX: `C:\Program Files\\ShareX\\ShareX.exe"`,
	slack: `"$env:USERPROFILE\\AppData\\Local\\slack\\slack.exe"`,
	teamViewer: `"C:\\Program Files\\TeamViewer\\TeamViewer.exe"`,
	vscode: 'code',
	youglish: 'https://youglish.com/',
	youtube: 'https://www.youtube.com/',
	zalo: `"$env:USERPROFILE\\AppData\\Local\\Programs\\Zalo\\Zalo.exe"`,
}
